### ISSUE TITLE
[Fullstack] Render Notes in Report Matches Figma

### ISSUE THREAD

**Issue by tawsifkamal** [GTBitsOfGood/southface#115]
### Description
As a user, I want to be able to see the notes that I currently have on each card on my report. These notes aren't rendered at the moment in the frontend for card. Make it so that all the notes are visible and matches Figma

Before clicking "view 3 more notes"
<img width="400" alt="image" src="https://user-images.githubusercontent.com/69729390/223549635-e57e795f-6a66-422c-8590-a8dbfca9d5e9.png">

After clicking "view 3 more notes"
<img width="400" alt="image" src="https://user-images.githubusercontent.com/69729390/223549668-9f527fd6-a5e0-40d4-b4fc-475f7a5c794f.png">

### Acceptance Criteria
- [x] Notes section is added on each card of the report
- [x] Notes are editable and deletable 
- [x] render only two notes by default
- [x] onClick of view "X" more notes, all notes are rendered
- [x] collapse all notes is implemented

### Other Notes
- check the figma flow Report Builder - view 3 more notes

**Comment by nmhossain02** [comment]
PR will likely include bug fixes to note editing (seems to be broken in main right now)
