### ISSUE TITLE
[Feature] Press "Enter" for Search Bar to Work

### ISSUE THREAD

**Issue by avayedawadi** [GTBitsOfGood/southface#170]
### Description

- Currently, in the search bar in the digital library, the blue button with enter needs to be physically pressed for the search to be done. 
- Make it so that by clicking enter, the search can also be completed. The physical button pressing should still work but clicking enter should make the search be completed.

![image](https://github.com/GTBitsOfGood/southface/assets/45608655/85902234-2ab6-4eca-8daa-07a93238d365)

### Acceptance Criteria

- [ ] When enter is clicked in the search bar, it searches through the digital library.
- [ ] Clicking the button still works for searching.

**Comment by Sky-De** [comment]
@avayedawadi hi, i would like to work on this 
Please assign this to me
Thanks
